# Prometheus가 sample-app /metrics 를 자동 수집하도록 설정
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app
  namespace: apps
  labels:
    # kube-prometheus-stack이 감지하는 라벨
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
